apiVersion: v1
kind: Pod
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  containers:
  - name: streamlit
    image: michaelfriedman1/streamlit_test:v2
    imagePullPolicy: Always
    ports:
    - containerPort: 8080